dist: trusty
sudo: required
language: node_js
node_js:
  - "7"

matrix:
  include:
    - os: linux
      dist: trusty
      before_install: 
      - sudo add-apt-repository ppa:ethereum/ethereum -y
      - sudo apt-get update
      - sudo apt-get install solc
    - os: osx
      before_install:
      - brew update
      - brew upgrade
      - brew tap ethereum/ethereum
      - brew install solidity
      - brew linkapps solidity

install: 
  - travis_retry sudo apt-get update -y
    #- sudo apt-get install npm
    #- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - node --version
  - npm --version
  - npm install
    #- npm install npm@latest -g
    #- npm --version
    #- sudo npm install web3 -y
    #- sudo npm install ethereumjs-testrpc -y
    #- sudo npm install -g web3 -y
  - npm install -g ethereumjs-testrpc -y

script: 
  - testrpc -d test &
  - chmod +x ./runtests.sh
  - ./runtests.sh
